### ISSUE TITLE
Problem installing CAMS Python bindings

### ISSUE THREAD

**Issue by leiteg** [caidao22/cams#1]
Hello!

I would like to test CAMS library but I am having problems with the Cython sources. I have succesfully built `libcams.a`, but running `pip install .` inside a virtual environment yields the following error message:

```
Processing /tmp/cams
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/tmp/cams/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/tmp/cams/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/cams/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-u1jx1atq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-u1jx1atq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-u1jx1atq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-u1jx1atq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I made sure to install `cython`  inside the virtualenv but it still didn't work. I am using Python 3.12.7 and Pip 24.3.1. Can you please help me? Thanks!

## Steps to reproduce

```bash
git clone https://github.com/caidao22/cams
cd cams
cp make.inc.example make.inc
make lib
python -m virtualenv venv
source venv/bin/activate
pip install cython
python install .
```

**Comment by leiteg** [comment]
So I was able to compile CAMS myself using a different method:.

```bash
# Inside the virtualenv
pip install setuptools cython
python setup.py install```

Still, it would be interesting to have this alternative method in the README in case other people have problems! :)

**Comment by caidao22** [comment]
> git clone https://github.com/caidao22/cams
> cd cams
> cp make.inc.example make.inc
> make lib
> python -m virtualenv venv
> source venv/bin/activate
> pip install cython
> python install .

The last step should be `pip install . `. Is this possibly the cause of the failure?

**Comment by leiteg** [comment]
> The last step should be `pip install . `. Is this possibly the cause of the failure?

I actually ran `pip install .` but I made a typo while writing the issue, my bad! I still get an error while installing with `pip install .`, but `python setup.py install` seems to work fine. Not sure why is this happening.
